# Default LLM configuration for pdf2markdown
# You can keep keys at the top level or under [llm].
# The application supports both. This example uses [llm].

[llm]
endpoint = "http://localhost:4000/v1/chat/completions"
model = "llama3-2-90b-instruct-v1:0"
api_key = "sk-1234"
